### ISSUE TITLE
00_ai_army_province_war.txt Issues

### ISSUE THREAD

**Issue by stackpoint** [Mxt-dot/BetterAI#1]
Got the following errors from the \Documents\Paradox Interactive\Europa Universalis IV\logs\error.log file:

```
[triggerimplementation.cpp:4420]: Unknown value yes in is_state_core trigger
[trigger.cpp:531]: Unknown trigger-type which in common/ai_army/00_ai_army_province_war.txt line : 62
[persistent.cpp:52]: Error: "Unexpected token: which, near line: 62
" in file: "common/ai_army/00_ai_army_province_war.txt" near line: 62
[trigger.cpp:531]: Unknown trigger-type value in common/ai_army/00_ai_army_province_war.txt line : 63
[persistent.cpp:52]: Error: "Unexpected token: value, near line: 63
" in file: "common/ai_army/00_ai_army_province_war.txt" near line: 63
[trigger.cpp:531]: Unknown trigger-type which in common/ai_army/00_ai_army_province_war.txt line : 69
[persistent.cpp:52]: Error: "Unexpected token: which, near line: 69
" in file: "common/ai_army/00_ai_army_province_war.txt" near line: 69
[trigger.cpp:531]: Unknown trigger-type value in common/ai_army/00_ai_army_province_war.txt line : 70
[persistent.cpp:52]: Error: "Unexpected token: value, near line: 70
" in file: "common/ai_army/00_ai_army_province_war.txt" near line: 70
[effect.cpp:855]: Unknown effect-type limit in events/ManaEvents.txt line : 131
[persistent.cpp:52]: Error: "Unexpected token: limit, near line: 131
" in file: "events/ManaEvents.txt" near line: 135
[effect.cpp:855]: Unknown effect-type option in events/ManaEvents.txt line : 741
[persistent.cpp:52]: Error: "Unexpected token: option, near line: 741
" in file: "events/ManaEvents.txt" near line: 743
[eventmanager.cpp:161]: Event #7100001 is missing a desc in events/ManaEvents.txt
[eventmanager.cpp:163]: Event #7100001 has no options in events/ManaEvents.txt
[eventmanager.cpp:165]: Event #7100001 is missing picture in events/ManaEvents.txt
```

**Comment by stackpoint** [comment]
```
[triggerimplementation.cpp:4420]: Unknown value yes in is_state_core trigger
```

is_state_core -> is_state

**Comment by stackpoint** [comment]
```
[trigger.cpp:531]: Unknown trigger-type which in common/ai_army/00_ai_army_province_war.txt line : 62
[persistent.cpp:52]: Error: "Unexpected token: which, near line: 62
" in file: "common/ai_army/00_ai_army_province_war.txt" near line: 62
[trigger.cpp:531]: Unknown trigger-type value in common/ai_army/00_ai_army_province_war.txt line : 63
[persistent.cpp:52]: Error: "Unexpected token: value, near line: 63
" in file: "common/ai_army/00_ai_army_province_war.txt" near line: 63
[trigger.cpp:531]: Unknown trigger-type which in common/ai_army/00_ai_army_province_war.txt line : 69
[persistent.cpp:52]: Error: "Unexpected token: which, near line: 69
" in file: "common/ai_army/00_ai_army_province_war.txt" near line: 69
[trigger.cpp:531]: Unknown trigger-type value in common/ai_army/00_ai_army_province_war.txt line : 70
[persistent.cpp:52]: Error: "Unexpected token: value, near line: 70
" in file: "common/ai_army/00_ai_army_province_war.txt" near line: 70
```

```
        	modifier = {
        		which = base_production/base_manpower
        		value = 4
        	}
```

to

```
        	modifier = {
        		base_production/base_manpower = 4
        	}
```

**Comment by stackpoint** [comment]
```
[effect.cpp:855]: Unknown effect-type limit in events/ManaEvents.txt line : 131
[persistent.cpp:52]: Error: "Unexpected token: limit, near line: 131
" in file: "events/ManaEvents.txt" near line: 135
```

I believe you can't use limit on capital_scope, instead use if to limit it instead.

```
					capital_scope = {
						if = {
							limit = {
									NOT = {
										development = 20
									}
							}
							add_base_production = 1
							add_scaled_local_dip_power = -10
```

**Comment by stackpoint** [comment]
```
[effect.cpp:855]: Unknown effect-type option in events/ManaEvents.txt line : 741
[persistent.cpp:52]: Error: "Unexpected token: option, near line: 741
" in file: "events/ManaEvents.txt" near line: 743
[eventmanager.cpp:161]: Event #7100001 is missing a desc in events/ManaEvents.txt
[eventmanager.cpp:163]: Event #7100001 has no options in events/ManaEvents.txt
[eventmanager.cpp:165]: Event #7100001 is missing picture in events/ManaEvents.txt
```

I'm not sure what's wrong with the options text, looks fine to me.

**Comment by stackpoint** [comment]
I just remembered that instead of reading the log file for errors that you can use this validator instead:

https://forum.paradoxplaza.com/forum/index.php?threads/the-validator-find-errors-quickly-and-with-minimal-pain.720987/

This thing is really useful for catching all sorts of things. For example did you know that "colonialism" is not a valid institution? I didn't and for some reason it's called "new_world_i" instead but thanks to the validator it'll let me know.

**Comment by Mxt-dot** [comment]
Hey there,

I honestly didn't expect such a quick response already. I knew that something was wrong with the ai_army script, since it didn't seem to have an effect ingame, though I pushed it aside for some other (personally) more important issues with the AI.

Thanks for pointing out the issues and also the link to the validator. I only saw one in a different project which checks for valid syntax, but that one was for linux so I wanted to have a look into it in a few days - after setting up everything in my VM, etc. etc...

Since this validator works in windows I will check it out today. 

The ManaEvents.txt is already fixed, I'll need to finish up the "devpushing institution" stuff and the file will be alright. Pretty ugly, since I didn't bother using variables and didn't refactor into different events due to logic-reasoning currently, BUT it should work.



> 
> 
> ```
> [effect.cpp:855]: Unknown effect-type limit in events/ManaEvents.txt line : 131
> [persistent.cpp:52]: Error: "Unexpected token: limit, near line: 131
> " in file: "events/ManaEvents.txt" near line: 135
> ```
> 
> I believe you can't use limit on capital_scope, instead use if to limit it instead.
> 
> ```
> 					capital_scope = {
> 						if = {
> 							limit = {
> 									NOT = {
> 										development = 20
> 									}
> 							}
> 							add_base_production = 1
> 							add_scaled_local_dip_power = -10
> ```

Though I didn't spot this one...

It's all currently a bit messy, though with a few core features finishing up everything should be fine in a few days.

**Comment by stackpoint** [comment]
I was going to make this bug report on steam workshop but then read that you were going to make a GitHub page so I just decided to wait and since it'd be easier here. Definitely looking forward to any progress you make, the AI in this game is definitely in dire need especially as they add more features that they aren't programmed to use (such as estates).

The validator takes a bit of work to setup because of the way 1.29 changed the mod folder but it's definitely worth it for a large project like yours.

Just one last thing before I close this issue. In the 00_ai_army_province_war.txt file, shouldn't the multipliers be above 1 to increase the importance of a province? 0.8 vs 1.2?

**Comment by Mxt-dot** [comment]
No no, that's the right thing to do! I appreciate the Issues and I will tackle this one here most probably today. I definitely don't like working without proper issue management, so feel free to keep this one open until the problem is fixed. If it takes forever then so be it :) 

> Definitely looking forward to any progress you make, the AI in this game is definitely in dire need especially as they add more features that they aren't programmed to use (such as estates).

Yep that's one of my main gripes with the AI aswell, paradox just leaves out crucial parts to make the AI more competitive. I absolutely hate the scripting language the mods are written in, but if this mod even helps a few people enjoy the game more then I accomplished my goal. Will also definitely support this for 1.30, and probably till the end of the eu4 update cycle. 

It doesn't have all the best "coding" practices since I want to make it work reliably instead of having a concise script. Currently I didn't bother writing a flow-chart for all the logic to make it easier perhaps, and I hope that time never comes! But if the performance starts to tank then I'll need to have a look at it aswell.

> The validator takes a bit of work to setup because of the way 1.29 changed the mod folder but it's definitely worth it for a large project like yours.

I finished up the devpushing institutions stuff and boy, oh boy, did the validator help! Thanks so much for that recommendation, as I found out so many syntax errors I didn't suspect I had! Especially the "PREV" scope, which I interpreted as "PREVPREV"... 

> Just one last thing before I close this issue. In the 00_ai_army_province_war.txt file, shouldn't the multipliers be above 1 to increase the importance of a province? 0.8 vs 1.2?

You might think, but actually no. I read the dev diary where they presented this file (in hindsight, everyone fell for it and thought it was actual AI improvements, heh) and there was one paragraph where they said lower score = higher priority. 
I didn't spot it right away aswell.

https://forum.paradoxplaza.com/forum/index.php?threads/eu4-development-diary-16th-of-october-2018.1124066/

> ...
> It will be evaluated when any of the following happens:
> - Whenever you gain or lose ownership or control of a province
> - Whenever a war starts or ends
> There are three ways to modify the score, you can multiply it, add to it or overwrite it. The factor can be negative and < 1.0 as well so the inverse operations are also possible.
> **Note that armies prefer the province with the lowest score.**
> ...

Really confused what they expect us to do with this file, as nobody implemented anything here, but I'll look into it regardless :)

**Comment by stackpoint** [comment]
> You might think, but actually no. I read the dev diary where they presented this file (in hindsight, everyone fell for it and thought it was actual AI improvements, heh) and there was one paragraph where they said lower score = higher priority.

This is actually hilarious because all the examples I could find of this file through google has it the wrong way. Good catch though.

**Comment by stackpoint** [comment]
Had a chance to play around with the mod last night and it looks like you've taken care of all the syntax errors with this issue so I'll be closing it.
