### ISSUE TITLE
Balance: Everything is so Hi-Dev it makes it difficult to map paint just because it's so pricey in mana

### ISSUE THREAD

**Issue by AgainstBronchitis** [Mxt-dot/BetterAI#34]
The province of Touggourt is a sprawling metropolis with 36 dev by 1530 because the AI force spawned an institution. The AI is so active in deving up that expansion is hampered, but artificially, just because the admin and AE cost shoots up.

Sometimes you need to eliminate a nation, not because you want their dev, but for strategic reasons, because you need their territory for passage or to prevent a coalition from forming, but now you have to eat much more AE and admin, or subject strength/liberty desire to do it.

I don't know what the solution is. Or if others will also find this a double-edged sword, but maybe stop very minor "road-kill" nations from doubling up their dev. They're not going to be a challenge either way but now they're a hassle.

**Comment by Mxt-dot** [comment]
Hmm I don't completely agree with it, cause even a minor nations can pose a threat in if you get 5+ of them together. It's unlikely, but possible.

The mod is intended to give players a challenge, so obviously this can be seen as part of it. If we look at coring cost reduction, it actually enables you to take those provinces for almost free if you can stack it up a bit. I'm not sure if it's possible to do WC without coring cost reduction with this mod, though it's supposed to be nearly impossible for nations without the precondition for it (coring cost reduction, diplo cost). 

If your nation doesn't have any coring cost reduction, you can also go for vassal annex since it's cheaper by default, so you can still lower it to 50% (with mission to like 40%) cost.

About the AE, that's a good point. Though you still get as much dev. So in the end, you're not as far on the map (as previously) but you will have the same dev and AE, so in the end you have more wars and nations to fight :)

**Comment by tagadanar** [comment]
just to give feedback, I personally enjoy the fact that you can't paint everything, so you still have competitors and challenges in late game, and AE add more diplomatics in the game, it feels more interesting to me.

**Comment by AgainstBronchitis** [comment]
You make a point, on the other hand it kind of detracts from realism/immersion when it's 1650 and Kildare is a 55 dev province and the biggest metropolis in Europe.

On the other hand, you can't really blame a better AI mod for getting the AI to play more optimally within the rules of the game.

The real problem is really from PDox, the fact that dev comes from a monarch.

**Comment by Mxt-dot** [comment]
I agree, and I even restricted the natives from doing any development since america would explode in dev. But for other nations I think the devcost is the necessary deterrent, so any nation doing much expansion will not have high dev provinces. 

As you say, it's inherently an issue that comes from the dev mechanic itself. Perhaps some other mods help in that regard, otherwise there's not much one can do :( 

I'm closing this for now to keep the list clean, though if there's any new observations, feedback etc. let me know!
